# Travis yml file inspired by scikit-bio
# Check on http://lint.travis-ci.org/ after modifying it!
language: python
env:
  - PYVERSION=3.5
before_install:
  - export MPLBACKEND='Agg'
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - export MINICONDA_PREFIX="$HOME/miniconda"
  - bash miniconda.sh -b -p $MINICONDA_PREFIX
  - export PATH="$MINICONDA_PREFIX/bin:$PATH"
  - conda config --set always_yes yes
  - conda install -c anaconda setuptools
  - conda update -q conda
  - conda info -a
  # https://discourse.gohugo.io/t/solved-hugo-v44-extended-and-relocation-errors-on-travis/13029/4
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6
install:
  - wget -q https://raw.githubusercontent.com/qiime2/environment-files/master/latest/staging/qiime2-latest-py36-linux-conda.yml
  - conda env create -q -n test_env --file qiime2-latest-py36-linux-conda.yml
  - conda install -c defaults tensorflow
  - conda install --yes -q -n test_env --file ci/conda_requirements.txt -c biocore
  - source activate test_env
  - pip install -e .
script:
  - make all
notifications:
  webhooks:
    on_success: change
    on_failure: always
